steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deploy.yaml'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/node-base/output_files/'
    targetFiles: deploy.yaml

- task: Kubernetes@0
  displayName: 'kubectl apply service'
  inputs:
    kubernetesServiceConnection: 'node-base-Kubernetes'
    command: apply
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/node-base/output_files/service.yaml'

- task: Kubernetes@0
  displayName: 'kubectl apply deployment'
  inputs:
    kubernetesServiceConnection: 'node-base-Kubernetes'
    command: apply
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/node-base/output_files/deploy.yaml'
