apiVersion: v1
kind: Service
metadata:
  name: node-base-svc
  labels:
    app: node-base-api
spec:
  ports:
  - port: 80
    targetPort: 3010
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: node-base-api
